version: '3'
services:
  flask:
    build:
      context: .
      dockerfile: Dockerfile_python
    container_name: flask_container
    volumes:
      - ./:/usr/src/app
    ports:
      - "5001:5000"
    environment:
      - FLASK_APP=backend/server.py
      - FLASK_ENV=development
    command: flask run --host=0.0.0.0

  vue:
    build:
      context: .
      dockerfile: Dockerfile_node
    container_name: vue_container
    tty: true
    volumes:
      - ./:/usr/src/app
    ports:
      - "5173:5173"
